---
title: "Getting Help"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Help}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Found a Bug?

If you encounter an unexpected error, incorrect result, or crash, please follow these steps.

1. Check that you are using the latest version of **spconform**:

   ```r
   remotes::install_github("amjed-droid/spconform")
   ```

2. Search the [existing issues](https://github.com/amjed-droid/spconform/issues) to see if the problem has already been reported.

3. If the issue has not been reported, open a new issue and include:
   - A minimal reproducible example.
   - Your `sessionInfo()` output.
   - The exact error message.
   - Any additional information that may help reproduce the problem.

## Documentation

```r
?scp_geostatistical
?scp_areal
?diagnose
?methods.spconform
vignette("spconform-intro", package = "spconform")
```

You may also consult the introductory vignette for an in-depth walkthrough of the package and its S3 diagnostic suite.

## GitHub Discussions

For usage questions, please open a thread in **GitHub Discussions** if it is enabled for the repository.

Alternatively, you can open an issue using the `question` label.

## Request a Feature

We welcome suggestions and feature requests.

Please open an issue describing:

- **What** you want to achieve.
- **Why** the current functionality is insufficient.
- A proposed API or interface, if you have one.
- A brief example of how you would expect the feature to work.

## Citation

If you use **spconform** in your research, please cite:

> Jabbar, A. S. (2026). *spconform: Conformal Prediction for Spatially and Spatio-Temporally Dependent Data in R* (Version 0.1.1) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.21862024

You can also obtain the citation directly from R:

```r
citation("spconform")
```

## Contact

**Author:** Ahmed Sattar Jabbar  
**Email:** ahmed.state.me@gmail.com  
**ORCID:** [0009-0006-4614-735X](https://orcid.org/0009-0006-4614-735X)
