#' Print Method for spconform Objects
#'
#' Prints a concise summary of an \code{spconform} prediction object, including
#' the data type, target coverage level, total number of prediction points, and
#' a preview of the first few prediction intervals.
#'
#' @param x An object of class \code{"spconform"}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @return Invisibly returns the input object \code{x}.
#' @export
print.spconform <- function(x, ...) {
  cat("<spconform> ", x$type, " conformal prediction\n", sep = "")
  cat(sprintf("Target coverage: %.1f%%\n", 100 * (1 - x$alpha)))
  n <- length(x$pred)
  cat(sprintf("Number of prediction points: %d\n", n))
  k <- min(n, 6)
  df <- data.frame(
    pred  = round(x$pred[seq_len(k)], 3),
    lower = round(x$lower[seq_len(k)], 3),
    upper = round(x$upper[seq_len(k)], 3)
  )
  print(df)
  if (n > k) cat(sprintf("... (%d more)\n", n - k))
  invisible(x)
}


#' Summary Method for spconform Objects
#'
#' Computes and displays summary statistics of the prediction interval widths
#' generated by an \code{spconform} object.
#'
#' @param object An object of class \code{"spconform"}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @return Invisibly returns the input object \code{object}.
#' @importFrom stats median
#' @export
summary.spconform <- function(object, ...) {
  width <- object$upper - object$lower
  cat("spconform summary\n")
  cat("------------------\n")
  cat("Type:                 ", object$type, "\n")
  cat("Target coverage:      ", sprintf("%.1f%%", 100 * (1 - object$alpha)), "\n")
  cat("Mean interval width:  ", round(mean(width, na.rm = TRUE), 4), "\n")
  cat("Median interval width:", round(stats::median(width, na.rm = TRUE), 4), "\n")
  invisible(object)
}


#' Plot Prediction Intervals for spconform Objects
#'
#' Visualizes the conformal prediction intervals and point predictions across
#' target locations or areal units. Optionally overlays true observations if provided.
#'
#' @param x An object of class \code{"spconform"}.
#' @param y_true Optional numeric vector of true observed responses matching \code{x$pred}.
#' @param ... Additional arguments passed to \code{\link[graphics]{plot}}.
#'
#' @return Invisibly returns the input object \code{x}.
#' @importFrom graphics plot points segments legend
#' @export
plot.spconform <- function(x, y_true = NULL, ...) {
  n <- length(x$pred)
  ord <- seq_len(n)
  
  ## حماية استخراج القيم وحساب نطاق المحور الصادي
  all_vals <- c(x$pred, x$lower, x$upper)
  if (!is.null(y_true)) {
    all_vals <- c(all_vals, y_true)
  }
  
  finite_vals <- all_vals[is.finite(all_vals)]
  if (length(finite_vals) == 0) {
    ylim_val <- c(0, 1)
  } else {
    ylim_val <- range(finite_vals, na.rm = TRUE)
    pad <- diff(ylim_val) * 0.05
    if (pad == 0) pad <- 0.5
    ylim_val <- c(ylim_val[1] - pad, ylim_val[2] + pad)
  }
  
  ## إعداد لوحة الرسم الأساسية
  graphics::plot(
    ord, x$pred,
    ylim = ylim_val,
    pch  = 19,
    xlab = if (identical(x$type, "areal")) "Areal Unit Index" else "Prediction Index",
    ylab = "Predicted / Response Value",
    main = paste0("spconform (", x$type, ") - ", round(100 * (1 - x$alpha)), "% intervals"),
    ...
  )
  
  ## رسم شرائط الفترات التنبؤية مع الحماية من القيم اللانهائية
  graphics::segments(
    ord, pmax(x$lower, ylim_val[1]),
    ord, pmin(x$upper, ylim_val[2]),
    col = "grey50", lwd = 1.5
  )
  
  ## إعادة إبراز نقاط التنبؤ
  graphics::points(ord, x$pred, pch = 19, col = "black")
  
  ## إضافة القيم الحقيقية ودليل الرسم في حال تمريرها
  if (!is.null(y_true)) {
    graphics::points(ord, y_true, col = "red", pch = 4, lwd = 1.5)
    graphics::legend(
      "topright",
      legend = c("Prediction", "Conformal Interval", "True Value"),
      col    = c("black", "grey50", "red"),
      pch    = c(19, NA, 4),
      lty    = c(NA, 1, NA),
      lwd    = c(NA, 1.5, 1.5),
      bty    = "n",
      cex    = 0.85
    )
  }
  
  invisible(x)
}


#' Empirical Coverage and Average Interval Width for an spconform Object
#'
#' Computes the empirical coverage rate and mean interval width by comparing
#' conformal prediction intervals against held-out ground truth responses.
#'
#' @param object An object of class \code{"spconform"}.
#' @param y_true Numeric vector of true observed values at the prediction
#'   locations. Must have the same length as \code{object$pred}.
#'
#' @return A named list with:
#' \describe{
#'   \item{coverage}{Proportion of true values falling within the prediction intervals.}
#'   \item{mean_width}{Mean width of the prediction intervals.}
#' }
#'
#' @examples
#' set.seed(1)
#' n <- 20
#' adj <- matrix(0, n, n)
#' for (i in 1:(n - 1)) { adj[i, i + 1] <- 1; adj[i + 1, i] <- 1 }
#' y <- cumsum(rnorm(n))
#' out <- scp_areal(y, adjacency = adj, alpha = 0.2)
#' coverage_report(out, y)
#'
#' @export
coverage_report <- function(object, y_true) {
  if (!inherits(object, "spconform")) {
    stop("'object' must be of class 'spconform'.")
  }
  if (length(y_true) != length(object$pred)) {
    stop("length(y_true) must match length(object$pred).")
  }
  
  covered <- (y_true >= object$lower) & (y_true <= object$upper)
  list(
    coverage   = mean(covered, na.rm = TRUE),
    mean_width = mean(object$upper - object$lower, na.rm = TRUE)
  )
}