#' Print Method for spconform Objects
#'
#' Displays a concise summary of the conformal prediction object including
#' model type, nominal target coverage, and a preview table of prediction intervals.
#'
#' @param x An object of class \code{"spconform"}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @return Invisibly returns the input object \code{x}.
#' @export
print.spconform <- function(x, ...) {
  cat("<spconform> ", x$type, " conformal prediction\n", sep = "")
  cat(sprintf("Target coverage: %.1f%%\n", 100 * (1 - x$alpha)))
  n <- length(x$pred)
  cat(sprintf("Number of prediction points: %d\n", n))
  k <- min(n, 6)
  df <- data.frame(
    pred = round(x$pred[seq_len(k)], 3),
    lower = round(x$lower[seq_len(k)], 3),
    upper = round(x$upper[seq_len(k)], 3)
  )
  print(df)
  if (n > k) cat(sprintf("... (%d more)\n", n - k))
  invisible(x)
}

#' Summary Method for spconform Objects
#'
#' Computes and displays summary statistics of the prediction interval widths
#' generated by an \code{spconform} object.
#'
#' @param object An object of class \code{"spconform"}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @return Invisibly returns the input object \code{object}.
#' @export
summary.spconform <- function(object, ...) {
  width <- object$upper - object$lower
  cat("spconform summary\n")
  cat("------------------\n")
  cat("Type:              ", object$type, "\n")
  cat("Target coverage:   ", sprintf("%.1f%%", 100 * (1 - object$alpha)), "\n")
  cat("Mean interval width:", round(mean(width), 4), "\n")
  cat("Median interval width:", round(stats::median(width), 4), "\n")
  invisible(object)
}

#' Plot Prediction Intervals for spconform Objects
#'
#' Plots point predictions and conformal prediction intervals across observation
#' indices, optionally overlaying true target values for visual evaluation.
#'
#' @param x An object of class \code{"spconform"}.
#' @param y_true Optional numeric vector of true observed responses at prediction locations.
#' @param ... Further graphical parameters passed to \code{\link[graphics]{plot}}.
#'
#' @return Invisibly returns the input object \code{x}.
#' @importFrom graphics points segments legend
#' @export
plot.spconform <- function(x, y_true = NULL, ...) {
  n <- length(x$pred)
  ord <- seq_len(n)
  ylim <- range(c(x$lower, x$upper, x$pred, y_true))
  plot(ord, x$pred, ylim = ylim, pch = 19, xlab = "Index", ylab = "Predicted value",
       main = paste0("spconform (", x$type, ") - ",
                      round(100 * (1 - x$alpha)), "% intervals"), ...)
  segments(ord, x$lower, ord, x$upper, col = "grey50")
  if (!is.null(y_true)) {
    points(ord, y_true, col = "red", pch = 4)
    legend("topright", legend = c("prediction", "truth"),
           pch = c(19, 4), col = c("black", "red"), bty = "n")
  }
  invisible(x)
}

#' Empirical Coverage and Average Interval Width for an spconform Object
#'
#' @param object An object of class \code{"spconform"}.
#' @param y_true Numeric vector of true observed values at the prediction
#'   locations, same length/order as \code{object$pred}.
#'
#' @return A named list with \code{coverage} (proportion of \code{y_true}
#'   falling within \code{[lower, upper]}) and \code{mean_width} (average
#'   interval width).
#'
#' @examples
#' set.seed(1)
#' n <- 20
#' adj <- matrix(0, n, n)
#' for (i in 1:(n - 1)) { adj[i, i + 1] <- 1; adj[i + 1, i] <- 1 }
#' y <- cumsum(rnorm(n))
#' out <- scp_areal(y, adjacency = adj, alpha = 0.2)
#' coverage_report(out, y)
#'
#' @export
coverage_report <- function(object, y_true) {
  if (!inherits(object, "spconform")) stop("'object' must be of class 'spconform'.")
  covered <- (y_true >= object$lower) & (y_true <= object$upper)
  list(
    coverage = mean(covered),
    mean_width = mean(object$upper - object$lower)
  )
}

#' Coerce an spconform Object to a Data Frame
#'
#' Converts a conformal prediction output object of class \code{"spconform"}
#' into a tidy \code{data.frame} containing coordinates (if present), point
#' predictions, lower/upper bounds, and interval widths.
#'
#' @param x An object of class \code{"spconform"}.
#' @param row.names \code{NULL} or a character vector giving row names.
#' @param optional Logical; passed to \code{as.data.frame}.
#' @param ... Additional arguments (currently unused).
#'
#' @return A \code{data.frame} with prediction columns \code{pred},
#'   \code{lower}, \code{upper}, \code{width}, and any coordinate columns.
#' @export
as.data.frame.spconform <- function(x, row.names = NULL, optional = FALSE, ...) {
  df <- data.frame(
    pred  = x$pred,
    lower = x$lower,
    upper = x$upper,
    width = x$upper - x$lower
  )
  if (!is.null(x$s0)) {
    coords <- as.data.frame(x$s0)
    if (ncol(coords) == 2 && all(names(coords) %in% c("V1", "V2"))) {
      names(coords) <- c("x", "y")
    }
    df <- cbind(coords, df)
  }
  as.data.frame(df, row.names = row.names, optional = optional, ...)
}

#' Extract Predictions and Intervals from an spconform Object
#'
#' Extracts point predictions or prediction interval bounds from a fitted
#' \code{spconform} object.
#'
#' @param object An object of class \code{"spconform"}.
#' @param interval Character string specifying the type of prediction intervals
#'   to extract: \code{"none"} (default, point predictions only) or
#'   \code{"prediction"} (matrix with fit, lwr, upr).
#' @param ... Further arguments passed to or from other methods.
#'
#' @return If \code{interval = "none"}, a numeric vector of point predictions.
#'   If \code{interval = "prediction"}, a numeric matrix with columns \code{fit},
#'   \code{lwr}, and \code{upr}.
#' @export
predict.spconform <- function(object, interval = c("none", "prediction"), ...) {
  interval <- match.arg(interval)
  if (interval == "none") {
    return(object$pred)
  } else {
    res <- cbind(fit = object$pred, lwr = object$lower, upr = object$upper)
    return(res)
  }
}

#' Extract Residuals from an spconform Object
#'
#' Calculates prediction residuals (observed minus fitted values) or
#' nonconformity scores for an \code{spconform} object given true responses.
#'
#' @param object An object of class \code{"spconform"}.
#' @param y_true Numeric vector of true observed responses at prediction locations.
#' @param type Character string indicating residual type: \code{"response"}
#'   (raw residuals \eqn{y - \hat{y}}) or \code{"abs"} (absolute nonconformity scores
#'   \eqn{|y - \hat{y}|}).
#' @param ... Further arguments passed to or from other methods.
#'
#' @return A numeric vector of residuals.
#' @export
residuals.spconform <- function(object, y_true, type = c("response", "abs"), ...) {
  if (missing(y_true) || is.null(y_true)) {
    stop("Argument 'y_true' must be provided to compute prediction residuals.")
  }
  if (length(y_true) != length(object$pred)) {
    stop("Length of 'y_true' must match the number of predictions.")
  }
  type <- match.arg(type)
  res <- y_true - object$pred
  if (type == "abs") {
    res <- abs(res)
  }
  res
}
